version: '3.8'

services:
  # node:
  #   build:
  #     dockerfile: ./src/docker/.dockerfile
  #   # environment:
  #   #   - NODE_ENV=production
  #   restart: always
  #   ports:
  #     - 8080:8080
  mariadb:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    # volumes:
    #   - m223_project_mariadb:/var/lib/mysql
    restart: always
    env_file:
      - ./src/docker/docker.env
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    restart: always
    env_file:
      - ./src/docker/docker.env
    ports:
      - 9200:80

# volumes:
#   m223_project_mariadb:
